import "./globals.css";
import { Inter } from "next/font/google";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Techvillage Customer Support Chatbot",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<StoreProvider>
			<html lang="en" >
				<body suppressHydrationWarning={true} className={inter.className}>{children}</body>
			</html>
		</StoreProvider>
	);
}
